[DHSCFT-120] Set up geography index
dhsc-govuk/FingertipsNext pull request #35
Opened 2024-12-23 18:15 UTC by adawari-thomas-bjss

# Description

Jira ticket: [DHSCFT-120](https://bjss-enterprise.atlassian.net/browse/DHSCFT-120)

## Changes

- Updated index creation to automate creating an index for search by geography
- Geography index fields are tentative and are likely to change
- Added unit tests to validate that the index was created with the expected fields and behaviours.

## Validation

![image](https://github.com/user-attachments/assets/8b8b2d71-2fdb-4edf-8ca7-4bb7e908b866)

2025-01-02 11:17 UTC, williamwillis11 requested changes
left a few comments

2025-01-06 11:10 UTC, gareth-allan-bjss commented on search-setup/package.json
> +    "test": "jest"
I think we'll need to wait until we can actually run the script to create indexes in Azure as part of an environment being deployed. As it is currently, when the CI job runs there will be no AI search instance/index to verify as we've not deployed anything yet.

2025-01-06 11:34 UTC, gareth-allan-bjss commented on search-setup/__tests__/search.test.ts
> +const searchEndpoint = getEnvironmentVariable("AI_SEARCH_SERVICE_ENDPOINT");
The README for this application points you at the `.env.example` file you need to copy, but you'll need details of an actual AI Search instance to access.

2025-01-06 11:41 UTC, adawari-thomas-bjss commented on search-setup/__tests__/search.test.ts
> +  const expectIndexToPopulated = async () => {
at the moment, it's only useful in this file as this file tests all the indexes that have been created. However, if tests for each index are moved to separate files later on, then a helper file would need to be created.

2025-01-06 13:36 UTC, gareth-allan-bjss reviewed
Looks good. A few comments, but nothing major.

2025-01-06 13:36 UTC, gareth-allan-bjss commented on search-setup/types.ts
> +interface DocumentValue extends IndicatorSearchData {
Shouldn't this be an `IndicatorDocumentValue` (and `DocumentResponse` should perhaps be a type that supports `value` fields that are either indicator documents or geography documents)?

2025-01-06 13:36 UTC, gareth-allan-bjss commented on search-setup/sample-data.ts
> +];
I think we should probably look to get some slightly more realistic areas into this data, as we know "City" isn't one of the area types we'll be using. I'm happy to do it in a later PR though, but just wanted to mention it while I remembered.

2025-01-06 15:47 UTC, andyevans-bjss commented
The data we need in the geography index is whatever can be searched - no point in adding properties that we don't need such as address line 1, 2 etc. Although postcode could be useful

2025-01-06 15:48 UTC, adawari-thomas-bjss commented on search-setup/types.ts
> +interface DocumentValue extends IndicatorSearchData {
removed the `DocumentValue` interface that adds the `@search.score` field, as it is not necessary because the tests that require this interface only check the length of the value array.

2025-01-06 17:39 UTC, gareth-allan-bjss approved these changes

2025-01-07 09:05 UTC, williamwillis11 commented on search-setup/__tests__/search.test.ts
> +const searchEndpoint = getEnvironmentVariable("AI_SEARCH_SERVICE_ENDPOINT");
thanks all

2025-01-07 09:11 UTC, williamwillis11 approved these changes

2025-01-07 09:19 UTC, gareth-allan-bjss approved these changes

2025-01-07 09:42 UTC, merged